- hosts: locals
  tasks:
    # Sunchronize repositories and Update System
    - name: Update pacman cache and System
      become: yes
      tags: update
      pacman:
        update_cache: true
        upgrade: true

    # Install JDK21 and Gradle
    - name: Install OpenJDK21 and Gradle (latest)
      become: yes
      tags: jdk
      pacman:
        name: 
          - jdk21-openjdk
          - gradle
        state: present

    # Install Docker
    - name: Install Docker and Compose
      become: yes
      tags: docker
      pacman:
        name: 
          - docker
          - docker-compose
        state: present

    # AUtoexec and Run Docker Service
    - name: Run Docker Service
      become: yes
      tags: docker
      ansible.builtin.systemd:
        name: docker.service
        state: started
        enabled: yes

    # Get current user
    - name: Get current user
      tags: docker
      ansible.builtin.command: whoami
      register: current_user

    # Add current user to docker group
    - name: Add current user to docker group
      become: yes
      tags: docker
      ansible.builtin.user:
        name: "{{ current_user.stdout }}"
        groups: docker
        append: yes
    
    # Install Far
    - name: Install far2l-git from AUR
      command: yay -S far2l-git --noconfirm

    # Install necessary softaware
    - name: Install necessary softaware
      become: yes
      tags: software
      pacman:
        name: 
          - dbeaver
          - visualvm
        state: present

    - name: Установка Bruno из AUR
      command: yay -S bruno-bin --noconfirm
    
    - name: Установка JMeter из AUR
      command: yay -S jmeter --noconfirm

    - name: Установка Sublime Text из AUR
      command: yay -S sublime-text-4 --noconfirm
